apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ovh32wyq4-python
  janus-idp.io/tekton: ovh32wyq4-python
  backstage.io/kubernetes-id: ovh32wyq4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ovh32wyq4-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
